### ISSUE TITLE
ASPNetImage error '80004003' 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kiddailey/aspnetimage#3]
```
After registering the component on a x64 Windows 2008 server (also tried in 
C:\Windows\SysWOW64) and running a test returns the error bellow on a line 
calling LoadImage.

ASPNetImage error '80004003' 
Object reference not set to an instance of an object. 


```

Original issue reported on code.google.com by `h...@nnes.be` on 7 Aug 2012 at 2:40

**Comment by kiddailey** [comment]
This could be due to a few issues, my first guess being with using a 32bit DLL on a 64bit OS (assuming you didn't compile it yourself).  Also could be due to image format.  If anyone reproduces this in the future, please provide a link to a sample image that causes the issue.
